default['graphite']['postgresUser'] = "graphite"
default['graphite']['postgresPassword'] = "password"
default['graphite']['postgresDBName'] = "graphite"
default['graphite']['graphiteSecretkey'] = "unsafekey"
default['graphite']['graphiteTimeZone'] = "America/Chicago"
